import {test} from 'node:test';
import assert from 'node:assert/strict';
import {applyAction,issSuggestion,effectiveAnnex,otherEntryRisk} from '../.domain-tests/contagiro.mjs';
import {accountingAction,dominioText,dre,horizontal,trialBalance,csv} from '../.domain-tests/reporting.mjs';
import {demoCompany,demoRecords} from '../.domain-tests/seed.mjs';
import {closeGates,allowed,totals} from '../.domain-tests/domain.mjs';
const actor={id:'contador-A',email:'contador@example.com'},client={id:'cliente-A',email:'cliente@example.com'},period='2026-08';
const c=()=>demoCompany('tenant-A','Empresa fictícia A'),rows=()=>demoRecords('tenant-A');
const apply=(records,change)=>[...records.filter(r=>!change.upserts.some(u=>r.id===u.id)),...change.upserts];
const activity={id:'activity-A',cnae:'8211300',name:'Serviços combinados de escritório',annex:'III',lc116:'17.02',nationalCode:'170201',municipalCode:'TESTE',municipalRequired:true,nbsRequired:false,nbs:'',basis:'Cenário fictício de teste do cadastro, confirmado pelo contador.',issRule:'Conferir incidência e legislação do município.'};
const matrix={type:'matrix_save',period,regime:'competencia',municipality:'São Paulo / SP',activities:[activity],confirm:true};
test('matrix confirmation is accountant-owned and later changes require an unused client request',()=>{
 let company=c(),records=rows();assert.throws(()=>applyAction(company,records,'owner',matrix),/perfil/);
 let change=applyAction(company,records,'accountant',matrix,'2026-09-08T00:00:00Z',actor);company=change.company;records=apply(records,change);assert.equal(company.data.tax.version,2);assert.equal(company.data.tax.activities[0].cnae,'8211300');assert.throws(()=>applyAction(company,records,'accountant',matrix),/Registro/);
 records=apply(records,applyAction(company,records,'owner',{type:'matrix_request',description:'Incluir atividade secundária',period},undefined,client));const request=records.find(r=>r.data.category==='tax_change');
 change=applyAction(company,records,'accountant',{...matrix,requestId:request.id},undefined,actor);company=change.company;records=apply(records,change);assert.equal(records.find(r=>r.id===request.id).data.status,'done');assert.throws(()=>applyAction(company,records,'accountant',{...matrix,requestId:request.id}),/ainda não aplicada/);
});
test('ISS is previous-month component; a public customer requires review even when retention is unselected',()=>{
 let company=c(),records=rows();const change=applyAction(company,records,'accountant',matrix,undefined,actor);company=change.company;records=apply(records,change);
 const estimate=issSuggestion(company,records,activity,'2026-09');assert.equal(estimate.reference,'2026-08');assert.equal(estimate.window,'2025-08 a 2026-07');assert.ok(estimate.ready);assert.ok(estimate.rate>0&&estimate.rate<.05);assert.equal(issSuggestion(company,records,activity,'2027-01').ready,false);
 records=apply(records,applyAction(company,records,'owner',{type:'contact_save',contactType:'customer',name:'Órgão fictício',municipality:'São Paulo / SP',publicBody:true},undefined,client));const contact=records.find(r=>r.kind==='contact');
 let ch=applyAction(company,records,'owner',{type:'invoice_create',contactId:contact.id,activityId:activity.id,service:'Serviço teste',serviceDate:'2026-08-10',serviceLocation:'São Paulo / SP',amount:'100,00',due:'2026-09-10'});records=apply(records,ch);const invoice=ch.upserts.find(r=>r.kind==='invoice');assert.equal(invoice.data.issStatus,'pending_review');assert.throws(()=>applyAction(company,records,'owner',{type:'invoice_simulate',id:invoice.id}),/revisão/);assert.throws(()=>applyAction(company,records,'owner',{type:'iss_review',id:invoice.id}),/perfil/);
 records=apply(records,applyAction(company,records,'accountant',{type:'iss_review',id:invoice.id,retained:true,percent:'2',basis:'Hipótese fictícia conferida para retenção'},undefined,actor));records=apply(records,applyAction(company,records,'owner',{type:'invoice_simulate',id:invoice.id}));assert.equal(records.find(r=>r.id===invoice.id).data.issAmount,200);
});
test('factor R needs a full validated history, with threshold inclusive at 28%',()=>{const r=rows(),a={...activity,annex:'factor_r'};assert.equal(effectiveAnnex(a,r,period).ready,false);r.filter(x=>x.kind==='history').forEach(x=>{x.data.payroll=x.data.revenue*.28;x.data.payrollValidated=true;});assert.equal(effectiveAnnex(a,r,period).annex,'III');r.find(x=>x.kind==='history').data.payroll-=100;assert.equal(effectiveAnnex(a,r,period).annex,'V');});
test('other entries create a per-company review and notification without tax or DRE inclusion',()=>{
 let records=rows();records=apply(records,applyAction(c(),records,'owner',{type:'classify',ids:['tenant-A:tx8'],category:'other_revenue'},undefined,client));assert.equal(otherEntryRisk(records).pending,1);assert.equal(records.filter(r=>r.kind==='task').length,1);assert.ok(records.some(r=>r.kind==='notification'));assert.equal(dre(records,period).excluded,200000);assert.equal(dre(records,period).values.revenue,2000000);assert.throws(()=>applyAction(c(),records,'accountant',{type:'review',note:'Conferido'}),/outras entradas/);
 records=apply(records,applyAction(c(),records,'accountant',{type:'review_other',id:'tenant-A:tx8',nature:'non_revenue',note:'Aporte do sócio conferido'},undefined,actor));assert.equal(dre(records,period).values.other,0);assert.equal(otherEntryRisk(records).pending,0);
});
test('recurrence generates once per company/competence, clamps day at month end, and one-off stays one-off',()=>{
 let records=rows();records=apply(records,applyAction(c(),records,'accountant',{type:'create_charge',frequency:'monthly',description:'Serviço mensal',amount:'150,00',due:'2026-08-31'}));const sub=records.find(r=>r.kind==='subscription');assert.ok(sub);
 records=apply(records,applyAction(c(),records,'accountant',{type:'generate_charges',period:'2026-09'}));assert.equal(records.find(r=>r.kind==='charge'&&r.period==='2026-09'&&r.data.subscriptionId===sub.id).data.due,'2026-09-30');const ch=applyAction(c(),records,'accountant',{type:'generate_charges',period:'2026-09'});assert.equal(ch.upserts.length,0);
 records=apply(records,applyAction(c(),records,'accountant',{type:'create_charge',frequency:'once',description:'Balanço',amount:'400,00',due:'2026-09-15'}));assert.equal(records.filter(r=>r.kind==='subscription').length,1);assert.throws(()=>applyAction(c(),records,'owner',{type:'create_charge'}),/perfil/);
});
test('archive and per-user acknowledgment preserve file content identity and append attributed events',()=>{
 let records=rows();records.push({id:'doc-A',kind:'document',period,data:{key:'original-key',sha256:'immutable-hash',name:'guia.pdf',category:'tax',version:1}});
 records=apply(records,applyAction(c(),records,'owner',{type:'ack_document',id:'doc-A'},undefined,client));records=apply(records,applyAction(c(),records,'accountant',{type:'ack_document',id:'doc-A'},undefined,actor));assert.equal(records.find(r=>r.id==='doc-A').data.acknowledgments.length,2);assert.throws(()=>applyAction(c(),records,'owner',{type:'ack_document',id:'doc-A'},undefined,client),/já foi/);
 records=apply(records,applyAction(c(),records,'owner',{type:'document_archive',id:'doc-A',reason:'Organização do arquivo'},undefined,client));assert.equal(records.find(r=>r.id==='doc-A').data.key,'original-key');assert.equal(records.find(r=>r.id==='doc-A').data.sha256,'immutable-hash');assert.ok(records.some(r=>r.kind==='document_event'&&r.data.event==='archived'));
 records=apply(records,applyAction(c(),records,'owner',{type:'document_restore',id:'doc-A',reason:'Consultar novamente'},undefined,client));assert.equal(records.find(r=>r.id==='doc-A').data.archivedAt,null);
});
test('payroll requests differ from computation records and official obligation transmission',()=>{let r=rows();r=apply(r,applyAction(c(),r,'owner',{type:'payroll_request',title:'Pró-labore',description:'Solicito revisão do valor',requestType:'Pró-labore'},undefined,client));assert.equal(r.filter(x=>x.data.category==='payroll').length,1);assert.throws(()=>applyAction(c(),r,'owner',{type:'payroll_save'}),/perfil/);r=apply(r,applyAction(c(),r,'accountant',{type:'payroll_save',gross:'3000,00',discounts:'330,00',charges:'0,00',note:'Resumo conferido na ferramenta de folha',status:'draft'}));assert.equal(r.find(x=>x.kind==='payroll').data.net,267000);assert.equal(r.filter(x=>x.kind==='task'&&x.data.category==='Folha / obrigações').length,3);});
test('DRE does not double count invoices, excludes loans and provides neutral zero-base comparisons',()=>{const r=rows();assert.equal(dre(r,period).values.revenue,2000000);assert.notEqual(dre(r,period).values.revenue,totals(r).billed+totals(r).received);assert.equal(horizontal(200,0),null);assert.equal(horizontal(-50,-100),.5);assert.equal(dre(r,'2026-07').hasData,false);assert.ok(csv([['=cmd','normal']]).includes("'=cmd"));});
test('accounting export requires matching reduced accounts, balanced openings, validated journals and accepted extra',()=>{
 let r=rows();const company=c();const accountAction=(a)=>accountingAction(company,r,'accountant',{...a,period},'2026-09-08T00:00:00Z',actor);
 const config={type:'accounting_save',taxId:'00000000000000',startPeriod:period,bankAccount:'1',accounts:[{code:'1',name:'Banco',group:'asset',opening:'0,00'},{code:'2',name:'Receita',group:'revenue',opening:'0,00'}],mappings:{revenue:'2'}};
 assert.throws(()=>accountingAction(company,r,'owner',{...config,period},undefined,client),/Somente/);assert.throws(()=>accountAction({...config,accounts:[{...config.accounts[0],opening:'1,00'},config.accounts[1]]}),/equilibrar/);r=apply(r,accountAction(config));
 r=apply(r,accountAction({type:'journal_save',date:'2026-08-10',debit:'1',credit:'2',amount:'100,25',memo:'Serviço teste'}));const journal=r.find(x=>x.kind==='journal');assert.throws(()=>dominioText(company,r,period),/revisão/);r=apply(r,accountAction({type:'journal_validate',id:journal.id}));assert.equal(trialBalance(r,period).difference,0);
 assert.throws(()=>accountAction({type:'accounting_close',confirm:true,note:'Conferido',requestId:'bad'}),/orçamento aceito/);
 r.push({id:'extra',kind:'request',period,data:{title:'Fechamento contábil',type:'Fechamento contábil / balanço',acceptedAt:'2026-09-08'}});r=apply(r,accountAction({type:'accounting_close',confirm:true,note:'Conferido',requestId:'extra'}));const output=dominioText(company,r,period);assert.ok(output.startsWith('|0000|00000000000000|\r\n'));assert.ok(output.includes('|6100|10/08/2026|1|2|100,25||Serviço teste|||'));assert.throws(()=>applyAction(company,r,'owner',{type:'classify',ids:['tenant-A:tx8'],category:'loan'}),/Reabra a revisão contábil/);
});
test('old scalar matrix endpoint is disabled and cross-company record IDs never resolve',()=>{assert.throws(()=>applyAction(c(),rows(),'accountant',{type:'tax_update'}),/matriz por atividades/);assert.throws(()=>applyAction(c(),rows(),'owner',{type:'document_archive',id:'other-tenant-doc',reason:'Excluir'}),/não encontrado/);assert.equal(allowed('finance','accounting_reopen'),false);assert.equal(closeGates(c(),rows())[0].done,false);});
