"use client";
// Diálogos das ações do portal (classificar, importar extrato, enviar documento, conferir ISS...).
import { useState, type FormEvent } from "react";
import { AlertCircle, CheckCircle2, ChevronRight, Download, FileCheck2, Loader2, Upload } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { categoryLabels, closeGates, dateLabel, expenseCategories, inPeriod, money, roleLabels, type Action, type Company, type WorkspaceState } from "@/lib/domain";
import ExtendedDialog, { extendedNames } from "./contagiro-dialog";
import { docCategories, Empty, Field, Info, SelectField, type PageKey } from "./ui";
type Props={state:WorkspaceState;company:Company;busy:boolean;dialog:{name:string;data:Record<string,any>};onClose:()=>void;onSaved:(s:WorkspaceState,message:string)=>void;act:(a:Action)=>Promise<boolean>;navigate:(p:PageKey)=>void};
const titles:Record<string,string>={classify:"Conferir e classificar",import:"Importar extrato bancário",invoice:"Preparar nota fiscal de serviço",document:"Anexar documento",request:"Nova solicitação",payable:"Cadastrar conta a pagar",charge:"Cadastrar cobrança interna",tax:"Validar matriz tributária",invite:"Preparar convite",review:"Registrar revisão do contador",reopen:"Reabrir competência",submit:"Enviar mês ao contador",approve:"Aprovar base para transmissão",simulate:"Simular emissão de NFS-e",cancel_invoice:"Cancelar rascunho ou nota simulada",ack:"Confirmar ciência do documento",quote:"Orçar serviço extra",accept_quote:"Aceitar orçamento",request_status:"Atualizar atendimento",report_payable:"Informar pagamento",report_charge:"Informar pagamento da cobrança",notifications:"Sua central de pendências",onboarding:"Um passo de cada vez"};
export default function PortalDialog({state,company,busy,dialog,onClose,onSaved,act,navigate}:Props){if(extendedNames.includes(dialog.name))return <ExtendedDialog {...{state,company,busy,dialog,onClose,act}}/>;const modal=dialog.name,[form,setForm]=useState(dialog.data),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<any>(null),[uploading,setUploading]=useState(false);const working=busy||uploading,records=state.records,invoices=inPeriod(records,"invoice",state.period),gates=closeGates(company,records,state.period),done=gates.filter(g=>g.done).length;
  const set=(key:string,value:any)=>setForm(f=>({...f,[key]:value}));const go=(page:PageKey)=>{onClose();navigate(page);};
  async function upload(endpoint:"import"|"documents",commit=false){if(!file||working)return;setUploading(true);try{const f=new FormData();f.set("companyId",company.id);f.set("period",form.period||state.period||"");f.set("previousId",form.previousId||"");f.set("version",String(preview?.version??company.version));f.set("file",file);f.set("account",form.account||"Conta principal");f.set("category",form.category||"monthly");f.set("commit",String(commit));const res=await fetch(`/api/${endpoint}`,{method:"POST",body:f});const data=await res.json();if(!res.ok)throw Error(data.error);if(endpoint==="import"&&!commit)setPreview(data);else onSaved(data.state,data.message);}catch(e){toast.error((e as Error).message);}finally{setUploading(false);}}
  function submit(e:FormEvent){e.preventDefault();if(working)return;const mapped:Record<string,string>={invoice:"invoice_create",request:"request_create",payable:"payable_create",charge:"create_charge",tax:"tax_update",quote:"quote_request",request_status:"set_request_status",simulate:"invoice_simulate",cancel_invoice:"invoice_cancel",ack:"ack_document"};if(modal==="import")void upload("import",!!preview);else if(modal==="document")void upload("documents");else void act({...form,type:mapped[modal]||modal,invoiceId:form.invoiceId==="none"?null:form.invoiceId});}
  return <Dialog open onOpenChange={v=>{if(!v&&!working)onClose();}}><DialogContent className={`product-dialog ${modal==="import"?"wide-dialog":""}`}><DialogHeader><DialogTitle>{titles[modal]}</DialogTitle><DialogDescription>{company.name} • {state.period} • demonstração</DialogDescription></DialogHeader><form onSubmit={submit}><div className="dialog-body">
  {modal==="classify"&&<><div className="selected-summary">{form.ids?.length} lançamento(s) selecionado(s)</div><Field label="Categoria"><SelectField value={form.category||""} onChange={v=>set("category",v)} options={Object.entries(categoryLabels).map(([value,label])=>({value,label}))}/></Field>{form.category==="other_revenue"&&<><Info>Use quando a origem precisa de esclarecimento. A contabilidade será avisada; a entrada não será tratada automaticamente como receita tributável.</Info><Field label="O que você sabe sobre esta entrada? (opcional)"><textarea value={form.justification||""} onChange={e=>set("justification",e.target.value)} maxLength={500}/></Field></>}{form.category==="revenue"&&<><Field label="Vincular à nota" hint="Recebimentos parciais são permitidos até o valor da nota."><SelectField value={form.invoiceId||"none"} onChange={v=>set("invoiceId",v)} options={[{value:"none",label:"Sem vínculo — informar justificativa"},...invoices.filter(i=>i.data.status==="simulated").map(i=>({value:i.id,label:`${i.data.customer} • ${money(i.data.amount)}`}))]}/></Field>{(!form.invoiceId||form.invoiceId==="none")&&<Field label="Justificativa da receita sem nota vinculada"><textarea value={form.justification||""} onChange={e=>set("justification",e.target.value)} placeholder="Ex.: recebimento de nota emitida no sistema anterior" maxLength={500}/></Field>}</>}{expenseCategories.includes(form.category)&&<><label className="check-option rule-option"><Checkbox checked={!!form.saveRule} onCheckedChange={v=>set("saveRule",!!v)}/><span>Sugerir nas próximas operações desta empresa</span></label>{form.saveRule&&<Field label="Identificador recorrente do fornecedor" hint="Use um trecho específico da descrição. Ex.: VIVO EMPRESAS."><Input required value={form.pattern||""} onChange={e=>set("pattern",e.target.value)} minLength={6}/></Field>}</>}<Info>Confirme valor, data e origem. A classificação também confirma a revisão de movimentos semelhantes.</Info></>}
  {modal==="import"&&<><Field label="Conta bancária" hint="Mantenha o mesmo nome para detectar duplicados nas próximas importações."><Input required value={form.account||""} onChange={e=>{set("account",e.target.value);setPreview(null);}}/></Field><label className="upload-area"><Upload size={28}/><strong>{file?file.name:"Selecione seu extrato OFX ou CSV"}</strong><span>Até 2 MB e 500 lançamentos • {state.period}</span><input type="file" accept=".csv,.ofx" onChange={e=>{setFile(e.target.files?.[0]||null);setPreview(null);}}/></label><a className="download-link" href="/modelo-extrato.csv" download><Download size={15}/>Baixar modelo CSV de demonstração</a>{preview&&<div className="import-preview"><div><strong>{preview.count} novos lançamentos</strong><span>{preview.duplicates} duplicado(s) identificado(s)</span></div>{preview.warning&&<Info warning>{preview.warning}</Info>}<div className="preview-scroll"><Table><TableHeader><TableRow><TableHead>Data</TableHead><TableHead>Descrição</TableHead><TableHead className="number-cell">Valor</TableHead></TableRow></TableHeader><TableBody>{preview.rows.slice(0,15).map((r:any)=><TableRow key={r.id}><TableCell>{dateLabel(r.date)}</TableCell><TableCell>{r.description}</TableCell><TableCell className="number-cell">{money(r.amount)}</TableCell></TableRow>)}</TableBody></Table></div>{preview.count>15&&<small>Prévia dos primeiros 15 lançamentos.</small>}</div>}</>}
  {modal==="invoice"&&<><Info warning>Esta etapa salva um rascunho. A simulação é separada e não gera nota fiscal oficial.</Info><Field label="Tomador do serviço"><Input required value={form.customer||""} onChange={e=>set("customer",e.target.value)} placeholder="Razão social ou nome"/></Field><Field label="Descrição do serviço"><textarea required value={form.service||""} onChange={e=>set("service",e.target.value)} maxLength={500}/></Field><div className="form-grid"><Field label="Valor bruto (R$)"><Input required inputMode="decimal" placeholder="0,00" value={form.amount||""} onChange={e=>set("amount",e.target.value)}/></Field><Field label="Vencimento previsto"><Input required type="date" value={form.due||""} onChange={e=>set("due",e.target.value)}/></Field></div></>}
  {modal==="document"&&<><Field label="Categoria do documento"><SelectField value={form.category||"monthly"} onChange={v=>set("category",v)} options={Object.entries(docCategories).filter(([k])=>k!=="bank").map(([value,label])=>({value,label}))}/></Field><label className="upload-area"><Upload size={27}/><strong>{file?file.name:"Selecione o documento"}</strong><span>PDF, JPG ou PNG • até 10 MB</span><input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label className="camera-option"><Upload size={18}/>Tirar foto do comprovante<input type="file" accept="image/*" capture="environment" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><Info>Para a etapa obrigatória do fechamento, escolha “Documentação mensal”.</Info></>}
  {modal==="request"&&<><Field label="Tipo de solicitação"><SelectField value={form.requestType||"Dúvida contábil"} onChange={v=>set("requestType",v)} options={["Dúvida contábil","Alteração cadastral","Documento","Consultoria","Fechamento contábil / balanço","Outro serviço"].map(v=>({value:v,label:v}))}/></Field><Field label="Assunto"><Input required value={form.title||""} onChange={e=>set("title",e.target.value)}/></Field><Field label="Como podemos ajudar?"><textarea required value={form.description||""} onChange={e=>set("description",e.target.value)} maxLength={2000}/></Field></>}
  {["payable","charge"].includes(modal)&&<><Field label="Descrição"><Input required value={form.description||""} onChange={e=>set("description",e.target.value)}/></Field><div className="form-grid"><Field label="Valor (R$)"><Input required inputMode="decimal" value={form.amount||""} onChange={e=>set("amount",e.target.value)}/></Field><Field label="Vencimento"><Input required type="date" value={form.due||""} onChange={e=>set("due",e.target.value)}/></Field></div>{modal==="payable"?<><Field label="Fornecedor cadastrado (opcional)"><SelectField value={form.supplierId||"none"} onChange={v=>set("supplierId",v)} options={[{value:"none",label:"Sem fornecedor vinculado"},...records.filter(r=>r.kind==="contact"&&["supplier","both"].includes(r.data.contactType)).map(r=>({value:r.id,label:r.data.name}))]}/></Field><Field label="Categoria"><SelectField value={form.category||"other_expense"} onChange={v=>set("category",v)} options={expenseCategories.map(value=>({value,label:categoryLabels[value]}))}/></Field></>:<Info>A cobrança será registrada internamente. Nenhum boleto/Pix será emitido.</Info>}</>}
  {modal==="tax"&&<><div className="form-grid"><Field label="Regime de apuração"><SelectField value={form.regime||"competencia"} onChange={v=>set("regime",v)} options={[{value:"competencia",label:"Competência"},{value:"caixa",label:"Caixa"}]}/></Field><Field label="Anexo"><SelectField value={form.annex||"III"} onChange={v=>set("annex",v)} options={["III","IV","V"].map(v=>({value:v,label:`Anexo ${v}`}))}/></Field></div><Field label="Município / UF"><Input required value={form.municipality||""} onChange={e=>set("municipality",e.target.value)}/></Field><Field label="Atividade / serviço"><Input required value={form.service||""} onChange={e=>set("service",e.target.value)}/></Field><label className="check-option"><Checkbox checked={!!form.factorR} onCheckedChange={v=>set("factorR",!!v)}/>Atividade sujeita ao fator R</label><Info>A matriz recebe uma nova versão e exige reconfirmação das receitas. Cenários não suportados suspendem a estimativa local.</Info></>}
  {modal==="invite"&&<><Field label="E-mail da pessoa"><Input required type="email" value={form.email||""} onChange={e=>set("email",e.target.value)}/></Field><Field label="Perfil nesta empresa"><SelectField value={form.role||"finance"} onChange={v=>set("role",v)} options={Object.entries(roleLabels).filter(([r])=>r!=="accountant").map(([value,label])=>({value,label}))}/></Field><Info>O convite fica preparado. Acesso de clientes e envio de e-mails serão habilitados na etapa de produção.</Info></>}
  {modal==="quote"&&<><Field label="Escopo e entregáveis"><textarea required value={form.scope||""} onChange={e=>set("scope",e.target.value)} maxLength={1000}/></Field><Field label="Valor do serviço extra (R$)"><Input required inputMode="decimal" value={form.amount||""} onChange={e=>set("amount",e.target.value)}/></Field><Info>O aceite do orçamento cria uma cobrança interna vinculada à demanda.</Info></>}
  {modal==="request_status"&&<><Field label="Situação"><SelectField value={form.status||"in_progress"} onChange={v=>set("status",v)} options={[{value:"in_progress",label:"Em atendimento"},{value:"done",label:"Concluída"}]}/></Field><Field label="Responsável"><Input required value={form.owner||""} onChange={e=>set("owner",e.target.value)}/></Field><Field label="Prazo previsto"><Input type="date" value={form.due||""} onChange={e=>set("due",e.target.value)}/></Field></>}
  {modal==="review"&&<><Field label="Parecer da revisão"><textarea required value={form.note||""} onChange={e=>set("note",e.target.value)} maxLength={1000}/></Field><Info>A revisão valida a base. A transmissão fiscal continua pendente.</Info></>}
  {modal==="reopen"&&<><Field label="Motivo da reabertura"><textarea required value={form.reason||""} onChange={e=>set("reason",e.target.value)} maxLength={500}/></Field><Info warning>A base volta à preparação. As confirmações de receitas e extratos, a revisão e a aprovação precisam ser refeitas.</Info></>}
  {modal==="submit"&&<><div className="confirmation-icon"><FileCheck2 size={30}/></div><p>As verificações estão completas. O envio preserva os dados desta competência para revisão do contador.</p><Info>Esse botão não transmite o PGDAS-D nem gera o DAS.</Info></>}
  {modal==="approve"&&<><p>Confirme a aprovação da base revisada desta empresa.</p><Info warning>O Integra Contador ainda não está conectado. A competência ficará aprovada com integração pendente, sem transmissão ou guia emitida.</Info></>}
  {modal==="simulate"&&<><p>Simular a emissão para <strong>{form.customer}</strong>?</p><Info warning>Um número “DEMO” será criado e o valor entrará no faturamento demonstrativo. Nenhuma nota será enviada ao emissor oficial.</Info></>}
  {modal==="cancel_invoice"&&<p>Confirmar o cancelamento do rascunho ou nota simulada de <strong>{form.customer}</strong>? O evento ficará no histórico.</p>}
  {modal==="ack"&&<><p>Declaro que tive acesso e tomei ciência do documento <strong>{form.name}</strong>.</p><Info>A confirmação registra sua identidade e horário. Não equivale ao pagamento de uma guia.</Info></>}
  {modal==="accept_quote"&&<><div className="quote-box"><span>Valor do serviço extra</span><strong>{money(form.amount||0)}</strong><p>{form.scope}</p></div><p>O aceite registra sua concordância e cria a cobrança interna vinculada à solicitação.</p></>}
  {["report_payable","report_charge"].includes(modal)&&<><p>Você está informando o pagamento de <strong>{form.name}</strong>.</p><Info>O status será “Pagamento informado”. A confirmação bancária ou do provedor é uma etapa separada.</Info></>}
  {modal==="notifications"&&<>{records.filter(r=>r.kind==="notification").slice().reverse().map(r=><div className="notification-card" key={r.id}><strong>{r.data.title}</strong><p>{r.data.body}</p><Button type="button" variant="outline" size="sm" onClick={()=>act({type:"read_notification",id:r.id})}>Registrar leitura</Button></div>)}{gates.filter(g=>!g.done).map(g=><button type="button" className="attention-row" key={g.id} onClick={()=>go(g.id==="categories"?"finance":g.id==="documents"?"documents":"closing")}><AlertCircle size={19}/><div><strong>{g.label}</strong><p>{g.detail}</p></div><ChevronRight size={16}/></button>)}{done===6&&<Empty icon={CheckCircle2} title="Tudo conferido"/>}<Info>Esta central mostra pendências no portal. E-mail e notificações no celular ainda dependem de configuração.</Info></>}
  {modal==="onboarding"&&<><p>Comece pela Aurora, uma empresa fictícia preparada para validar o fluxo.</p>{[{title:"Confira o extrato",text:"Teste a sugestão de internet e classifique as demais entradas e saídas.",page:"finance"},{title:"Organize os documentos",text:"Anexe um PDF de teste na categoria Documentação mensal.",page:"documents"},{title:"Envie para a contabilidade",text:"Confirme extratos e receitas, envie o mês e registre a revisão no painel do contador.",page:"closing"}].map((s,i)=><button className="onboarding-step" type="button" key={s.title} onClick={()=>go(s.page as PageKey)}><span>{i+1}</span><div><strong>{s.title}</strong><p>{s.text}</p></div><ChevronRight size={18}/></button>)}<Info>Use arquivos fictícios na validação. As integrações oficiais serão conectadas antes do piloto com empresas reais.</Info></>}
  </div><DialogFooter><Button type="button" variant="outline" disabled={working} onClick={onClose}>{["notifications","onboarding"].includes(modal)?"Fechar":"Cancelar"}</Button>{!["notifications","onboarding"].includes(modal)&&<Button type="submit" className="primary-button" disabled={working||(["import","document"].includes(modal)&&!file)||(modal==="import"&&preview?.count===0)}>{working?<><Loader2 size={17} className="spin"/>Salvando…</>:modal==="import"?(preview?"Confirmar importação":"Conferir arquivo"):modal==="classify"?"Confirmar classificação":modal==="invoice"?"Salvar rascunho":modal==="submit"?"Enviar para revisão":modal==="ack"?"Confirmar minha ciência":"Confirmar"}</Button>}</DialogFooter></form></DialogContent></Dialog>;
}
