import { type Action, type Activity, type Change, type Company, type Entry, type Role, allowed, categoryLabels, expenseCategories, getPeriod, inPeriod, money, normalize, parseMoney, reduceAction, requireThat, textField, totals, validDate, PERIOD, exigirMesDeEmissao, exigirMesEncerrado, hojeBrasilia, mesApuracao, mesAtual } from './domain';

export const monthShift=(month:string,n:number)=>{const d=new Date(`${month}-15T12:00:00Z`);d.setUTCMonth(d.getUTCMonth()+n);return d.toISOString().slice(0,7);};
export const validPeriod=(s:string)=>/^\d{4}-(0[1-9]|1[0-2])$/.test(s);
export const amountText=(n:number)=>((n||0)/100).toFixed(2).replace('.',',');
export function effectiveAnnex(activity:Activity, records:Entry[],period:string){
 if(activity.annex!=='factor_r')return {annex:activity.annex,ratio:null,ready:true};
 const months=Array.from({length:12},(_,i)=>monthShift(period,i-12));
 const history=months.map(m=>records.find(r=>r.kind==='history'&&r.period===m));
 const complete=history.every(r=>r&&typeof r.data.revenue==='number'&&typeof r.data.payroll==='number'&&r.data.payrollValidated);
 const revenue=history.reduce((s,r)=>s+(r?.data.revenue||0),0),payroll=history.reduce((s,r)=>s+(r?.data.payroll||0),0);
 const ready=complete&&revenue>0&&period.startsWith('2026');const ratio=ready?payroll/revenue:null;
 return {annex:ratio===null?null:ratio>=.28?'III':'V',ratio,ready};
}
// Limited 2026 estimate. No automatic retention decision and no full-DAS-rate substitution.
export function issSuggestion(company:Company,records:Entry[],activity:Activity|undefined,servicePeriod:string){
 const reference=monthShift(servicePeriod,-1),result={ready:false,rate:null as number|null,reference,window:`${monthShift(reference,-12)} a ${monthShift(reference,-1)}`,annex:null as string|null,reason:'Histórico / regra fora do cenário de estimativa. Informe a alíquota conferida pelo contador.'};
 if(!activity||!servicePeriod.startsWith('2026')||!company.data.tax.validated)return result;
 const annex=effectiveAnnex(activity,records,reference).annex;
 const history=Array.from({length:12},(_,i)=>records.find(r=>r.kind==='history'&&r.period===monthShift(reference,i-12)));
 if(!annex||history.some(r=>!r||typeof r.data.revenue!=='number'))return result;
 const rbt=history.reduce((s,r)=>s+r!.data.revenue,0);
 // First four tiers only: excludes sublimites, start-up rules and redistribution exceptions.
 const tables:Record<string,number[][]>={III:[[18000000,.06,0,.335],[36000000,.112,936000,.32],[72000000,.135,1764000,.325],[180000000,.16,3564000,.325]],IV:[[18000000,.045,0,.445],[36000000,.09,810000,.40],[72000000,.102,1242000,.40],[180000000,.14,3978000,.40]],V:[[18000000,.155,0,.14],[36000000,.18,450000,.17],[72000000,.195,990000,.19],[180000000,.205,1710000,.21]]};
 const tier=tables[annex]?.find(t=>rbt<=t[0]);if(!tier||rbt<=0)return result;
 const rate=((rbt*tier[1]-tier[2])/rbt)*tier[3];
 return {...result,annex,rate,ready:true,reason:'Parcela efetiva de ISS do mês anterior • estimativa sujeita à confirmação do contador'};
}
export function otherEntryRisk(records:Entry[],period=PERIOD){const t=totals(records,period);return {amount:t.otherRevenue,main:t.received,high:t.otherRevenue>0&&t.otherRevenue>t.received,pending:inPeriod(records,'transaction',period).filter(r=>r.data.category==='other_revenue'&&!r.data.otherReview).length};}
export const notificationText='Precisamos esclarecer a origem desta entrada. PIX é apenas o meio de pagamento. A classificação não define tributação: transferências, aportes e outras operações podem ter tratamentos diferentes. A contabilidade vai conferir a natureza e a eventual necessidade de documento fiscal.';
export function applyAction(company:Company,records:Entry[],role:Role,a:Action,now=new Date().toISOString(),actor={id:'test',email:'teste@example.com'}):Change{
 requireThat(allowed(role,a.type),'Seu perfil não permite esta operação.',403);
 const agora=new Date(now),period=a.type==='invoice_create'?mesAtual(agora):a.period||mesApuracao(agora);requireThat(validPeriod(period),'Competência inválida.');
 if(['submit','review','approve','confirm_check','confirm_no_movement'].includes(a.type))exigirMesEncerrado(period,agora);
 const p=getPeriod(records,period),upserts:Entry[]=[];let changed:Company|undefined,detail='';
 const frozen=inPeriod(records,'accounting',period).some(r=>r.data.type==='close'&&r.data.status==='reviewed');
 if(['history_save','classify','undo_classification','invoice_create','invoice_cancel','invoice_simulate','iss_review','matrix_save','review_other'].includes(a.type))requireThat(!frozen,'Reabra a revisão contábil antes de alterar a base exportável.');
 const make=(kind:Entry['kind'],data:Record<string,any>,id=crypto.randomUUID(),at=period)=>({id,kind,period:at,data});
 const add=(kind:Entry['kind'],data:Record<string,any>,id?:string,at?:string)=>{const r=make(kind,data,id,at);upserts.push(r);return r;};
 const select=(id:string,kind:Entry['kind'])=>{const r=records.find(r=>r.id===id&&r.kind===kind);requireThat(r,'Registro não encontrado nesta empresa.',404);return r;};
 const update=(r:Entry,data:Record<string,any>)=>{const next=upserts.find(x=>x.id===r.id)||r;const n={...next,data:{...next.data,...data}};upserts.push(n);return n;};
 const open=()=>requireThat(p?.data.status==='open','Reabra esta competência antes de alterar a base.');
 const notify=(title:string,body:string,sourceId:string)=>add('notification',{title,body,sourceId,createdAt:now,audience:'client',readBy:[],channel:'portal'});
 switch(a.type){
 case 'period_open':{requireThat(!p,'A competência já existe.');requireThat(period<=mesAtual(agora),'Não é possível abrir uma competência futura.');requireThat(period>='2025-01'&&period<='2030-12','Informe uma competência entre 2025 e 2030.');add('period',{status:'open',bankConfirmed:false,revenueConfirmed:false});detail=`Competência ${period} aberta, sem copiar movimentos anteriores.`;break;}
 case 'history_save':{requireThat(role==='accountant','Histórico restrito ao contador.',403);open();requireThat(validPeriod(a.historyPeriod),'Competência do histórico inválida.');const revenue=parseMoney(a.revenue),payroll=parseMoney(a.payroll);requireThat(revenue>=0&&payroll>=0,'Histórico não pode ser negativo.');const old=records.find(r=>r.kind==='history'&&r.period===a.historyPeriod);const evidence=select(a.evidenceId,'document');add('history',{...old?.data,revenue,payroll,payrollValidated:true,source:textField(a.source,'Fonte do histórico',500),evidenceId:evidence.id,validatedAt:now,validatedBy:actor.email},old?.id,a.historyPeriod);update(p!,{revenueConfirmed:false});detail='Receita auferida e folha elegível do mês registradas para os cálculos por vigência.';break;}
 case 'matrix_request':{const evidence=role==='accountant'?textField(a.evidence,'Referência da solicitação do cliente',500):'Solicitação no portal';add('request',{title:'Alteração da matriz tributária',description:textField(a.description,'Alteração solicitada',2000),type:'Alteração tributária',category:'tax_change',status:'new',requestedBy:actor.email,requestedAt:now,clientRequestEvidence:evidence,createdAt:now});detail='Solicitação de alteração enviada ao contador. A matriz permanece vigente.';break;}
 case 'matrix_save':{
  open();requireThat(a.confirm===true,'Confirme a conferência do cadastro e das atividades.');
  let req:Entry|undefined;if(company.data.tax.confirmedAt){req=select(a.requestId,'request');requireThat(req.data.category==='tax_change'&&!req.data.appliedAt&&req.data.clientRequestEvidence,'Vincule uma solicitação do cliente ainda não aplicada.');}
  requireThat(Array.isArray(a.activities)&&a.activities.length>0&&a.activities.length<=20,'Cadastre de 1 a 20 atividades exercidas.');
  const activities:Activity[]=a.activities.map((v:any)=>{requireThat(/^\d{7}$/.test(String(v.cnae).replace(/\D/g,'')),'CNAE deve ter sete dígitos.');requireThat(['III','IV','V','factor_r'].includes(v.annex),'Selecione a regra de anexo da atividade.');requireThat(/^\d{2}\.\d{2}$/.test(v.lc116),'Item da LC 116 no formato 00.00.');requireThat(/^\d{6}$/.test(v.nationalCode),'Código de tributação nacional deve ter seis dígitos.');return {id:v.id||crypto.randomUUID(),cnae:String(v.cnae).replace(/\D/g,''),name:textField(v.name,'Atividade executada'),annex:v.annex,lc116:v.lc116,nationalCode:v.nationalCode,municipalRequired:!!v.municipalRequired,municipalCode:v.municipalRequired?textField(v.municipalCode,'Código municipal',30):String(v.municipalCode||'').slice(0,30),nbsRequired:!!v.nbsRequired,nbs:v.nbsRequired?textField(v.nbs,'NBS',20):String(v.nbs||'').slice(0,20),basis:textField(v.basis,'Fundamento do enquadramento',600),issRule:textField(v.issRule,'Regra municipal / local de incidência e retenção',600)};});
  requireThat(new Set(activities.map(v=>v.id)).size===activities.length,'Cada atividade precisa ter identificação própria.');requireThat(['caixa','competencia'].includes(a.regime),'Regime inválido.');
  const tax={...company.data.tax,regime:a.regime,municipality:textField(a.municipality,'Município / UF'),service:activities[0].name,annex:activities[0].annex==='factor_r'?'V':activities[0].annex,factorR:activities.some(v=>v.annex==='factor_r'),activities,version:company.data.tax.version+1,validated:true,confirmedAt:now,confirmedBy:actor.email,effectiveFrom:period};
  changed={...company,data:{...company.data,active:true,tax}};
  add('tax_version',{before:company.data.tax,after:tax,requestId:req?.id||null,confirmedBy:actor.email,confirmedAt:now});
  if(req)update(req,{status:'done',appliedAt:now,taxVersion:tax.version});update(p!,{revenueConfirmed:false});
  detail=`Matriz v${tax.version} confirmada pelo contador; ${activities.length} atividade(s). Alterações posteriores exigem solicitação.`;break;
 }
 case 'contact_save':{requireThat(role!=='issuer'||a.contactType==='customer','Emissores podem cadastrar apenas tomadores.',403);requireThat(['supplier','customer','both'].includes(a.contactType),'Escolha fornecedor ou tomador.');const existing=a.id?select(a.id,'contact'):null;const taxId=String(a.taxId||'').replace(/\D/g,'');requireThat(!taxId||[11,14].includes(taxId.length),'CPF/CNPJ deve ter 11 ou 14 dígitos.');requireThat(!taxId||!records.some(r=>r.kind==='contact'&&r.id!==existing?.id&&r.data.taxId===taxId),'Este CPF/CNPJ já está no cadastro desta empresa.');const zip=String(a.zip||'').replace(/\D/g,''),ibge=String(a.ibge||'').replace(/\D/g,''),uf=String(a.uf||'').trim().toUpperCase();requireThat(!zip||zip.length===8,'CEP deve ter 8 dígitos.');requireThat(!ibge||ibge.length===7,'Código IBGE do município deve ter 7 dígitos.');requireThat(!uf||/^[A-Z]{2}$/.test(uf),'UF inválida.');const street=String(a.street||'').trim().slice(0,125),streetNumber=String(a.streetNumber||'').trim().slice(0,10),complement=String(a.complement||'').trim().slice(0,60),district=String(a.district||'').trim().slice(0,60);add('contact',{name:textField(a.name,'Nome / razão social'),contactType:a.contactType,taxId,email:String(a.email||'').slice(0,180),phone:String(a.phone||'').slice(0,30),municipality:textField(a.municipality,'Município / UF'),address:(street?[street,streetNumber,complement,district].filter(Boolean).join(', '):String(a.address||'')).slice(0,250),zip,street,streetNumber,complement,district,ibge,uf,municipalRegistration:String(a.municipalRegistration||'').slice(0,30),publicBody:!!a.publicBody,updatedAt:now},existing?.id);detail='Cadastro salvo apenas na memória desta empresa.';break;}
 case 'invoice_create':{
  // O mês corrente é aberto automaticamente na primeira nota.
  if(p)open();else add('period',{status:'open',bankConfirmed:false,revenueConfirmed:false});requireThat(company.data.tax.confirmedAt&&company.data.tax.activities?.length,'O contador deve confirmar a matriz por atividades antes de preparar notas.');
  const activity=company.data.tax.activities.find(v=>v.id===a.activityId);requireThat(activity,'Escolha uma atividade exercida e confirmada.');
  const contact=select(a.contactId,'contact');requireThat(['customer','both'].includes(contact.data.contactType),'Escolha um tomador cadastrado.');
  requireThat(validDate(a.serviceDate)&&a.serviceDate.startsWith(period),`A data da prestação deve estar no mês atual (${period}).`);requireThat(a.serviceDate<=hojeBrasilia(agora),'A data da prestação não pode ser futura.');
  const amount=parseMoney(a.amount);requireThat(amount>0&&validDate(a.due),'Revise o valor e vencimento.');
  const location=textField(a.serviceLocation,'Município / UF da prestação');const needsISS=!!a.issRetained||!!contact.data.publicBody||normalize(location)!==normalize(company.data.tax.municipality);
  add('invoice',{customer:contact.data.name,contactId:contact.id,contactSnapshot:contact.data,service:textField(a.service,'Serviço',500),serviceDate:a.serviceDate,serviceLocation:location,activityId:activity.id,activitySnapshot:activity,taxVersion:company.data.tax.version,amount,due:a.due,issRetained:!!a.issRetained,issStatus:needsISS?'pending_review':'not_indicated',issSuggestion:issSuggestion(company,records,activity,period),status:'draft',createdAt:now});if(p)update(p,{revenueConfirmed:false});detail='Rascunho preparado com os códigos da atividade. Casos de ISS aguardam conferência do contador.';break;
 }
 case 'iss_review':{open();const invoice=select(a.id,'invoice');exigirMesDeEmissao(invoice.period,agora);requireThat(invoice.data.status==='draft','A conferência de ISS deve ocorrer no rascunho.');const retained=!!a.retained;const percent=Number(String(a.percent||'0').replace(',','.'));requireThat(Number.isFinite(percent)&&percent>=0&&percent<=5,'Informe a parcela de ISS entre 0% e 5%, conforme a regra conferida.');requireThat(!retained||percent>0,'Informe a alíquota de ISS retida.');update(invoice,{issRetained:retained,issRate:retained?percent/100:0,issAmount:retained?Math.round(invoice.data.amount*percent/100):0,issStatus:'reviewed',issReview:{by:actor.email,at:now,basis:textField(a.basis,'Fundamento e município de incidência',1000)}});update(p!,{revenueConfirmed:false});detail='Incidência e retenção de ISS confirmadas pelo contador. A alíquota total do DAS não foi usada como retenção.';break;}
 case 'invoice_simulate':{const invoice=select(a.id,'invoice');exigirMesDeEmissao(invoice.period,agora);requireThat(invoice.data.issStatus!=='pending_review','Aguarde a revisão da incidência e retenção de ISS pelo contador.');requireThat(!invoice.data.taxVersion||invoice.data.taxVersion===company.data.tax.version,'A matriz mudou. Cancele o rascunho e prepare outro com a configuração vigente.');return reduceAction(company,records,role,a,now);}
 case 'classify':{
  const base=reduceAction(company,records,role,a,now);upserts.push(...base.upserts);detail=base.detail;
  for(const id of a.ids){const t=select(id,'transaction');const modified=upserts.find(r=>r.id===id)!;modified.data.otherReview=null;
   if(a.category!=='other_revenue'){const task=records.find(r=>r.id===`${id}:other-review`);if(task)update(task,{status:'done',completedAt:now,evidence:'Movimento reclassificado; ver histórico de classificação.'});}
   if(a.category==='other_revenue'){const taskId=`${id}:other-review`;const prev=records.find(r=>r.id===taskId);add('task',{...prev?.data,title:'Esclarecer outras entradas',description:t.data.description,status:'pending',sourceId:id,owner:'Contador responsável',due:monthShift(period,1)+'-10',category:'Receitas a esclarecer'},taskId);notify('Entrada aguardando esclarecimento',notificationText,id);}
  }
  const risk=otherEntryRisk([...records.filter(r=>!upserts.some(x=>x.id===r.id)),...upserts],period);if(a.category==='other_revenue'&&risk.high)notify('Outras entradas superam os recebimentos de serviços',`Há ${money(risk.amount)} em outras entradas e ${money(risk.main)} em recebimentos da atividade. Essa proporção merece revisão conjunta; não define, por si só, receita tributável.`,period);
  break;
 }
 case 'undo_classification':{const base=reduceAction(company,records,role,a,now);upserts.push(...base.upserts);for(const t of base.upserts.filter(r=>r.kind==='transaction')){const task=records.find(r=>r.id===`${t.id}:other-review`);if(task)update(task,{status:t.data.category==='other_revenue'?'pending':'done',evidence:'Lote desfeito; ver histórico.'});}detail=base.detail;break;}
 case 'review_other':{open();const t=select(a.id,'transaction');requireThat(t.data.category==='other_revenue','Esta entrada já foi reclassificada.');requireThat(['service','operating','financial','non_revenue'].includes(a.nature),'Escolha a natureza após a conferência.');update(t,{otherReview:{nature:a.nature,note:textField(a.note,'Parecer do contador',1000),by:actor.email,at:now}});const task=records.find(r=>r.id===`${t.id}:other-review`);if(task)update(task,{status:'done',completedAt:now});update(p!,{revenueConfirmed:false});detail='Natureza da entrada revisada. O tratamento fiscal será confirmado na apuração.';break;}
 case 'review':{requireThat(otherEntryRisk(records,period).pending===0,'Revise as outras entradas antes de concluir a revisão fiscal.');return reduceAction(company,records,role,a,now);}
 case 'confirm_no_movement':{open();requireThat(inPeriod(records,'transaction',period).length===0,'Há movimentos importados neste mês.');update(p!,{noMovement:!!a.value,bankConfirmed:!!a.value,revenueConfirmed:false});detail='Declaração de ausência de movimentação registrada.';break;}
 case 'task_save':{const r=a.id?select(a.id,'task'):null;requireThat(validDate(a.due),'Informe o prazo da entrega.');add('task',{...r?.data,title:textField(a.title,'Obrigação / tarefa'),description:String(a.description||'').slice(0,1000),category:textField(a.category||'Entrega','Tipo'),owner:textField(a.owner,'Responsável'),due:a.due,status:r?.data.status||'pending',createdAt:r?.data.createdAt||now},r?.id);detail='Tarefa salva na agenda da contabilidade.';break;}
 case 'task_status':{const r=select(a.id,'task');requireThat(['pending','in_progress','done'].includes(a.status),'Situação inválida.');update(r,{status:a.status,completedAt:a.status==='done'?now:null,evidence:a.status==='done'?textField(a.evidence,'Referência da entrega',500):r.data.evidence});detail='Andamento da entrega atualizado.';break;}
 case 'lead_save':{const email=textField(a.email,'E-mail').toLowerCase();requireThat(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email),'E-mail inválido.');add('lead',{name:textField(a.name,'Nome do interessado'),email,package:textField(a.package,'Pacote escolhido'),status:'incomplete',source:'Registro manual • validação',createdAt:now,owner:textField(a.owner||'Comercial','Responsável')});detail='Cadastro incompleto registrado para acompanhamento comercial.';break;}
 case 'lead_status':{const r=select(a.id,'lead');requireThat(['incomplete','contacted','converted','lost'].includes(a.status),'Etapa inválida.');update(r,{status:a.status,note:textField(a.note,'Registro do acompanhamento',500),updatedAt:now});detail='Acompanhamento comercial atualizado.';break;}
 case 'create_charge':{
  requireThat(role==='accountant','Somente a contabilidade registra cobranças.',403);const amount=parseMoney(a.amount);requireThat(amount>0&&validDate(a.due),'Revise valor e vencimento.');requireThat(['once','monthly'].includes(a.frequency),'Escolha cobrança avulsa ou mensal.');
  const description=textField(a.description,'Serviço cobrado');const subscription=a.frequency==='monthly'?add('subscription',{description,amount,start:a.due.slice(0,7),day:Number(a.due.slice(8)),active:true,createdAt:now}):null;
  add('charge',{description,amount,due:a.due,status:'pending',source:a.frequency==='monthly'?'subscription':'one_off',frequency:a.frequency,subscriptionId:subscription?.id||null,provider:'not_connected',createdAt:now},undefined,a.due.slice(0,7));detail=a.frequency==='monthly'?'Serviço mensal salvo e primeira cobrança interna criada.':'Cobrança avulsa criada uma única vez.';break;
 }
 case 'generate_charges':{let count=0;for(const sub of records.filter(r=>r.kind==='subscription'&&r.data.active&&r.data.start<=period)){if(records.some(r=>r.kind==='charge'&&r.period===period&&r.data.subscriptionId===sub.id))continue;const last=new Date(Date.UTC(Number(period.slice(0,4)),Number(period.slice(5)),0)).getUTCDate();add('charge',{description:sub.data.description,amount:sub.data.amount,due:`${period}-${String(Math.min(last,sub.data.day)).padStart(2,'0')}`,status:'pending',source:'subscription',frequency:'monthly',subscriptionId:sub.id,provider:'not_connected',createdAt:now});count++;}detail=`${count} cobrança(s) interna(s) criada(s) em ${period}; recorrências já geradas foram preservadas.`;break;}
 case 'subscription_pause':{const r=select(a.id,'subscription');update(r,{active:!r.data.active});detail='Recorrência atualizada; cobranças anteriores permanecem no histórico.';break;}
 case 'payable_create':{const change=reduceAction(company,records,role,a,now);if(a.supplierId&&a.supplierId!=='none'){const supplier=select(a.supplierId,'contact');requireThat(['supplier','both'].includes(supplier.data.contactType),'Escolha um fornecedor desta empresa.');change.upserts[0].data.supplierId=supplier.id;change.upserts[0].data.supplierSnapshot=supplier.data;}return change;}
 case 'payroll_request':{const r=add('request',{title:textField(a.title,'Assunto da folha'),description:textField(a.description,'Informações da solicitação',2000),type:textField(a.requestType,'Tipo de solicitação'),category:'payroll',status:'new',createdAt:now,requestedBy:actor.email});add('task',{title:`Folha: ${r.data.title}`,category:'Folha / eSocial',owner:'Departamento pessoal',due:validDate(a.due)?a.due:monthShift(period,1)+'-05',status:'pending',requestId:r.id});detail='Solicitação de folha recebida; acompanhamento disponível ao cliente.';break;}
 case 'employee_save':{requireThat(['employee','prolabore'].includes(a.employeeType),'Selecione funcionário ou pró-labore.');const r=a.id?select(a.id,'employee'):null;const amount=parseMoney(a.amount);requireThat(amount>=0&&validDate(a.start),'Revise remuneração e início.');add('employee',{name:textField(a.name,'Nome'),employeeType:a.employeeType,job:textField(a.job,'Cargo / função'),amount,start:a.start,esocialRegistration:String(a.esocialRegistration||'').slice(0,60),status:a.status==='inactive'?'inactive':'active',updatedAt:now},r?.id);detail='Registro interno de pessoal salvo. Não houve envio ao eSocial.';break;}
 case 'payroll_save':{const r=records.find(r=>r.kind==='payroll'&&r.period===period);const gross=parseMoney(a.gross),discounts=parseMoney(a.discounts),charges=parseMoney(a.charges);requireThat(gross>=0&&discounts>=0&&discounts<=gross&&charges>=0,'Revise proventos, descontos e encargos.');const evidence=a.evidenceId?select(a.evidenceId,'document'):null;requireThat(a.status!=='reviewed'||evidence,'Anexe e selecione a memória de cálculo para confirmar a folha.');add('payroll',{gross,discounts,charges,net:gross-discounts,status:a.status==='reviewed'?'reviewed':'draft',source:'Valores de cálculo externo informados pelo contador',evidenceId:evidence?.id||null,note:textField(a.note,'Memória / referência do cálculo',1000),by:actor.email,updatedAt:now},r?.id);for(const title of ['eSocial • remuneração e fechamento','DCTFWeb • conferir declaração e guia','FGTS Digital • conferir quando aplicável']){if(!records.some(t=>t.kind==='task'&&t.period===period&&t.data.title===title))add('task',{title,category:'Folha / obrigações',owner:'Departamento pessoal',due:validDate(a.due)?a.due:monthShift(period,1)+'-15',status:'pending',description:'Prazo interno de acompanhamento. Confirmar aplicabilidade e vencimento oficial.'});}detail='Resumo da folha salvo; obrigações internas criadas para conferência e registro de entrega.';break;}
 case 'document_archive':case 'document_restore':{const d=select(a.id,'document');if(d.data.category==='people')requireThat(role==='accountant'||role==='owner','Documento de pessoal restrito.',403);const archive=a.type==='document_archive';requireThat(archive?!d.data.archivedAt:!!d.data.archivedAt,'O documento já está nesta situação.');const reason=textField(a.reason,'Motivo',500);update(d,{archivedAt:archive?now:null,archivedBy:archive?actor.email:null});add('document_event',{documentId:d.id,event:archive?'archived':'restored',actor:actor.email,actorId:actor.id,at:now,detail:reason});detail=`${d.data.name}: ${archive?'arquivado':'restaurado'}. Original e histórico preservados.`;break;}
 case 'ack_document':{const d=select(a.id,'document');requireThat(d.data.category!=='people'||['owner','accountant'].includes(role),'Documento restrito.',403);const acks=d.data.acknowledgments||[];requireThat(!acks.some((x:any)=>x.actorId===actor.id),'Sua ciência já foi registrada.');update(d,{acknowledgedAt:now,acknowledgments:[...acks,{actorId:actor.id,actor:actor.email,at:now}]});add('document_event',{documentId:d.id,event:'acknowledged',actor:actor.email,actorId:actor.id,at:now,detail:'Ciência expressa deste arquivo / versão.'});detail='Sua ciência foi registrada com identidade, horário e versão do arquivo.';break;}
 case 'record_document_delivery':{const d=select(a.id,'document');add('document_event',{documentId:d.id,event:'external_delivery_reported',actor:actor.email,actorId:actor.id,at:now,detail:textField(a.evidence,'Referência do envio externo',1000)});detail='Referência do envio externo registrada. Não equivale a confirmação técnica de entrega ou leitura.';break;}
 case 'read_notification':{const r=select(a.id,'notification');const readBy=r.data.readBy||[];if(!readBy.some((v:any)=>v.id===actor.id))update(r,{readBy:[...readBy,{id:actor.id,email:actor.email,at:now}]});detail='Leitura da notificação registrada.';break;}
 default:return reduceAction(company,records,role,a,now);
 }
 return {upserts:[...new Map(upserts.map(r=>[r.id,r])).values()],company:changed,event:a.type,detail};
}
