import { type Company, type Entry, type Action, type Change, type Role, categoryLabels, dateLabel, expenseCategories, getPeriod, inPeriod, requireThat, textField, parseMoney, validDate } from './domain';
import { monthShift, validPeriod } from './contagiro';
export const dreLines=[['revenue','Receitas de serviços'],['other','Outras receitas operacionais conferidas'],['deductions','(-) Tributos pagos'],['net','Receita líquida gerencial'],['cost','(-) Custos dos serviços'],['people','(-) Pessoal'],['operating','(-) Despesas operacionais'],['operatingResult','Resultado operacional'],['financial','Resultado financeiro'],['result','Resultado gerencial do período']] as const;
export function dre(records:Entry[],period:string){
 const tx=inPeriod(records,'transaction',period),p=getPeriod(records,period),v:Record<string,number>={revenue:0,other:0,deductions:0,cost:0,people:0,operating:0,financial:0};let excluded=0,pending=0;
 for(const r of tx){const {category:c,amount:n,otherReview}=r.data;if(!c||r.data.needsReview){pending++;continue;}
  if(c==='revenue')v.revenue+=n;else if(c==='other_revenue'){
   if(!otherReview){excluded+=n;pending++;}else if(otherReview.nature==='service')v.revenue+=n;else if(otherReview.nature==='operating')v.other+=n;else if(otherReview.nature==='financial')v.financial+=n;
  }else if(c==='taxes')v.deductions+=n;else if(c==='service_cost')v.cost+=n;else if(c==='people')v.people+=n;else if(c==='bank')v.financial+=n;else if(expenseCategories.includes(c))v.operating+=n;
 }
 v.net=v.revenue+v.other+v.deductions;v.operatingResult=v.net+v.cost+v.people+v.operating;v.result=v.operatingResult+v.financial;
 return {period,values:v,excluded,pending,hasData:tx.length>0||!!p?.data.noMovement,closed:!!p&&['submitted','reviewed','approved'].includes(p.data.status),basis:'caixa',margin:v.revenue+v.other>0?v.result/(v.revenue+v.other):null};
}
export function horizontal(current:number,prior:number|undefined){if(prior===undefined||prior===0)return null;return (current-prior)/Math.abs(prior);}
export function dreNotes(records:Entry[],period:string){const current=dre(records,period),prior=dre(records,monthShift(period,-1)),notes:string[]=[];
 if(current.pending)notes.push(`${current.pending} movimento(s) ainda precisam de classificação ou esclarecimento; o resultado é parcial.`);
 if(current.values.result<0)notes.push('As despesas classificadas superam as receitas reconhecidas nesta visão de caixa. Revise custos e prazos de recebimento.');
 if(prior.hasData&&current.hasData){const delta=horizontal(current.values.revenue,prior.values.revenue);if(delta!==null)notes.push(`Recebimentos de serviços ${delta>=0?'cresceram':'caíram'} ${Math.abs(delta*100).toFixed(1).replace('.',',')}% em relação ao mês anterior.`);const exp=(v:Record<string,number>)=>-(v.deductions+v.cost+v.people+v.operating+Math.min(0,v.financial));const d=horizontal(exp(current.values),exp(prior.values));if(d!==null&&d>.1)notes.push(`Despesas cresceram ${(d*100).toFixed(1).replace('.',',')}%. Confira quais categorias explicam o aumento.`);if(prior.values.result<=0&&current.values.result>0)notes.push('O resultado passou a positivo em relação ao mês anterior.');}
 else notes.push('A comparação horizontal ficará disponível quando houver outra competência com movimentos classificados.');
 if(!current.closed)notes.push('Competência em preparação: os valores podem mudar até o fechamento.');return notes;
}
export type Account={code:string;name:string;group:'asset'|'liability'|'equity'|'revenue'|'expense';opening:number};
export function accountingConfig(records:Entry[]){return records.find(r=>r.kind==='accounting'&&r.data.type==='matrix');}
export function trialBalance(records:Entry[],period:string){const config=accountingConfig(records)?.data,accounts=(config?.accounts||[]) as Account[];const journals=records.filter(r=>r.kind==='journal'&&r.period<=period&&r.period>=(config?.startPeriod||period)&&r.data.status==='validated');const balances=accounts.map(a=>({...a,debit:journals.filter(j=>j.data.debit===a.code).reduce((s,j)=>s+j.data.amount,0),credit:journals.filter(j=>j.data.credit===a.code).reduce((s,j)=>s+j.data.amount,0)})).map(a=>({...a,closing:a.opening+a.debit-a.credit}));return {balances,difference:balances.reduce((s,a)=>s+a.closing,0),debit:balances.reduce((s,a)=>s+a.debit,0),credit:balances.reduce((s,a)=>s+a.credit,0)};}
const clean=(s:unknown)=>String(s??'').replace(/[|\r\n\t]/g,' ').trim();
export function dominioText(company:Company,records:Entry[],period:string){const config=accountingConfig(records)?.data;requireThat(config,'Configure a matriz contábil.');const close=inPeriod(records,'accounting',period).find(r=>r.data.type==='close');requireThat(close&&close.data.status==='reviewed','Conclua a revisão contábil antes de exportar.');const tx=inPeriod(records,'journal',period);requireThat(tx.length>0&&tx.every(r=>r.data.status==='validated'),'Valide todos os lançamentos do lote.');requireThat(/^\d{14}$/.test(config.taxId),'Informe o CNPJ do destino da importação.');const rows=[`|0000|${config.taxId}|`];tx.forEach((r,i)=>{rows.push(`|6000|X||CG${period.replace('-','')}${String(i+1).padStart(5,'0')}||`);rows.push(['','6100',dateLabel(r.data.date),r.data.debit,r.data.credit,(r.data.amount/100).toFixed(2).replace('.',','),'',clean(r.data.memo),'',config.branch||'',''].join('|')+'|');});return rows.join('\r\n')+'\r\n';}
export function csv(rows:unknown[][]){return '\uFEFF'+rows.map(row=>row.map(cell=>{let s=String(cell??'');if(/^[=+@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}).join(';')).join('\r\n');}
export function accountingAction(company:Company,records:Entry[],role:Role,a:Action,now:string,actor:{id:string;email:string}):Change|null{
 if(!['accounting_save','journal_generate','journal_save','journal_validate','accounting_close','accounting_reopen'].includes(a.type))return null;
 requireThat(role==='accountant','Somente o contador configura e fecha a contabilidade.',403);const period=a.period;requireThat(validPeriod(period)&&getPeriod(records,period),'Competência indisponível.');const upserts:Entry[]=[];let detail='';const add=(kind:Entry['kind'],data:Record<string,any>,id=crypto.randomUUID())=>upserts.push({id,kind,period,data});
 const config=accountingConfig(records),close=inPeriod(records,'accounting',period).find(r=>r.data.type==='close');
 if(a.type!=='accounting_reopen')requireThat(close?.data.status!=='reviewed','Reabra a revisão contábil antes de alterar o lote.');
 if(a.type==='accounting_save'){
  requireThat(!records.some(r=>r.kind==='accounting'&&r.data.type==='close'&&r.data.status==='reviewed'),'Reabra os fechamentos contábeis antes de alterar a matriz.');
  requireThat(Array.isArray(a.accounts)&&a.accounts.length>=2&&a.accounts.length<=200,'Cadastre de 2 a 200 contas.');const accounts:Account[]=a.accounts.map((v:any)=>{requireThat(/^\d{1,12}$/.test(v.code),'Código reduzido da conta deve ser numérico.');requireThat(['asset','liability','equity','revenue','expense'].includes(v.group),'Grupo contábil inválido.');return {code:v.code,name:textField(v.name,'Nome da conta'),group:v.group,opening:parseMoney(v.opening||'0')};});requireThat(new Set(accounts.map(x=>x.code)).size===accounts.length,'Há códigos de conta repetidos.');requireThat(accounts.reduce((s,v)=>s+v.opening,0)===0,'Os saldos iniciais devedores e credores precisam se equilibrar.');requireThat(validPeriod(a.startPeriod),'Competência inicial inválida.');requireThat(accounts.some(x=>x.code===a.bankAccount),'Escolha a conta bancária no plano.');const mappings:Record<string,string>={};for(const [key,val] of Object.entries(a.mappings||{})){requireThat(Object.hasOwn(categoryLabels,key)&&accounts.some(x=>x.code===val),'Mapeamento de categoria inválido.');mappings[key]=String(val);}
  const taxId=String(a.taxId||'').replace(/\D/g,'');requireThat(/^\d{14}$/.test(taxId),'CNPJ do destino deve ter 14 dígitos.');add('accounting',{type:'matrix',accounts,mappings,bankAccount:a.bankAccount,startPeriod:a.startPeriod,taxId,branch:String(a.branch||'').replace(/\D/g,'').slice(0,10),version:(config?.data.version||0)+1,confirmedBy:actor.email,updatedAt:now},config?.id);detail='Matriz contábil e saldos iniciais salvos. Contas devem corresponder ao cadastro do Domínio.';
 }else if(a.type==='journal_generate'){
  requireThat(config,'Configure a matriz contábil antes de preparar o lote.');let count=0;
  for(const t of inPeriod(records,'transaction',period)){
   if(records.some(j=>j.kind==='journal'&&j.data.sourceId===t.id))continue;
   const opposite=config.data.mappings[t.data.category];requireThat(t.data.category&&!t.data.needsReview&&opposite,`Revise a classificação e o mapeamento de: ${t.data.description}.`);requireThat(t.data.category!=='other_revenue'||t.data.otherReview,'Revise a natureza de outras entradas antes de contabilizar.');const debit=t.data.amount>0?config.data.bankAccount:opposite,credit=t.data.amount>0?opposite:config.data.bankAccount;requireThat(debit!==credit,'A conta bancária e a contrapartida não podem ser iguais.');
   add('journal',{date:t.data.date,debit,credit,amount:Math.abs(t.data.amount),memo:t.data.description,sourceId:t.id,sourceSnapshot:t.data,matrixVersion:config.data.version,status:'draft',createdAt:now});count++;
  }detail=`${count} lançamento(s) preparados a partir do extrato. Confira a competência e acrescente provisões e ajustes antes de validar.`;
 }else if(a.type==='journal_save'){
  requireThat(config,'Configure a matriz contábil.');const old=a.id?records.find(r=>r.id===a.id&&r.kind==='journal'&&r.period===period):null;requireThat(!a.id||old,'Lançamento indisponível.');requireThat(validDate(a.date)&&a.date.startsWith(period),'Data fora da competência.');const amount=parseMoney(a.amount);requireThat(amount>0&&a.debit!==a.credit,'Revise valor e contrapartida.');for(const code of [a.debit,a.credit])requireThat(config.data.accounts.some((x:Account)=>x.code===code),'Conta inexistente na matriz.');add('journal',{...old?.data,date:a.date,debit:a.debit,credit:a.credit,amount,memo:textField(a.memo,'Histórico',500),sourceSnapshot:old?.data.sourceId?records.find(r=>r.id===old.data.sourceId)?.data:old?.data.sourceSnapshot,matrixVersion:config.data.version,status:'draft',updatedAt:now},old?.id);detail='Lançamento salvo para validação contábil.';
 }else if(a.type==='journal_validate'){
  const journal=records.find(r=>r.id===a.id&&r.kind==='journal'&&r.period===period);requireThat(journal&&journal.data.status==='draft','Lançamento não disponível para validação.');requireThat(journal.data.matrixVersion===config?.data.version,'Matriz alterada; revise e salve novamente o lançamento.');add('journal',{...journal.data,status:'validated',validatedBy:actor.email,validatedAt:now},journal.id);detail='Lançamento validado pelo contador.';
 }else if(a.type==='accounting_reopen'){
  requireThat(close?.data.status==='reviewed','Não há revisão fechada.');add('accounting',{...close.data,status:'open',reopenedAt:now,reason:textField(a.reason,'Motivo da reabertura',500)},close.id);detail='Revisão contábil reaberta; o arquivo anterior permanece no histórico.';
 }else{
  const journals=inPeriod(records,'journal',period);for(const journal of journals){if(journal.data.sourceId)requireThat(JSON.stringify(journal.data.sourceSnapshot)===JSON.stringify(records.find(r=>r.id===journal.data.sourceId)?.data),'Um movimento de origem mudou; revise e valide o lançamento novamente.');}
  requireThat(journals.length>0&&journals.every(r=>r.data.status==='validated'),'Valide todos os lançamentos.');requireThat(a.confirm===true,'Confirme a conferência de saldos, provisões e documentos.');const trial=trialBalance(records,period);requireThat(trial.difference===0,'O balancete não está equilibrado.');
  const req=records.find(r=>r.kind==='request'&&r.id===a.requestId&&r.data.type==='Fechamento contábil / balanço'&&r.data.acceptedAt);requireThat(req,'Vincule o serviço extra com orçamento aceito.');
  add('accounting',{type:'close',status:'reviewed',reviewedAt:now,reviewedBy:actor.email,note:textField(a.note,'Parecer contábil',1000),requestId:req.id,snapshot:{matrix:config?.data,journals,trial}},close?.id);detail='Lote contábil revisado e liberado para exportação. Balanço oficial e assinatura são concluídos no sistema contábil.';
 }
 return {upserts,event:a.type,detail};
}
